name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag fedora42:latest
      
    - name: Build Fedora 42 specific image
      run: docker build . --file Dockerfile-fedora42 --tag fedora42-specific:latest
      
    - name: Scan Image with anchore
      uses: anchore/scan-action@v4
      with:
        image: fedora42:latest 
        fail-build: false
        acs-report-enable: true
        
    - name: Upload Anchore Scan Report
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: results.sarif 
              
    - name: Login to Docker Registry
      if: github.event_name == 'push'
      uses: docker/build-push-action@v5
      with:
        registry: ${{ secrets.docker_url }} 
        repository: fedora42 
        username: ${{ secrets.docker_username }}
        password: ${{ secrets.docker_password }}
    
