name: Docker Image CI

on:
  push:
    branches: [ master ]
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag fedora41:latest
      
    - name: Generate SBOM for Docker image
      uses: anchore/sbom-action@v0
      with:
        image: fedora41:latest
        format: spdx-json
        output-file: fedora41-sbom.spdx.json
        
    - name: Upload SBOM as artifact
      uses: actions/upload-artifact@v4
      with:
        name: fedora41-sbom
        path: fedora41-sbom.spdx.json
      
    - name: Scan Image with anchore
      uses: anchore/scan-action@v3
      with:
        image: fedora41:latest 
        fail-build: false
        output-format: sarif
        
    - name: Upload Anchore Scan Report
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: results.sarif 
              
    - name: Login to Docker Registry
      uses: docker/login-action@v3
      if: success()
      with:
        registry: ${{ secrets.docker_url }} 
        username: ${{ secrets.docker_username }}
        password: ${{ secrets.docker_password }}
        
    - name: Push Docker image
      if: success()
      run: |
        docker tag fedora41:latest ${{ secrets.docker_url }}/fedora41:latest
        docker push ${{ secrets.docker_url }}/fedora41:latest
    
